<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="105" passed="105">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="799" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:06Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="799" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:06Z">
      <class name="cn.vko.core.db.util.TestEntityUtil">
        <test-method status="PASS" signature="testEName2TName()[pri:0, instance:cn.vko.core.db.util.TestEntityUtil@3abc8e1e]" name="testEName2TName" duration-ms="1" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testGetTableName()[pri:0, instance:cn.vko.core.db.util.TestEntityUtil@3abc8e1e]" name="testGetTableName" duration-ms="0" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
      </class>
      <class name="cn.vko.core.db.util.TestDbSqlUtil">
        <test-method status="PASS" signature="init()[pri:0, instance:cn.vko.core.db.util.TestDbSqlUtil@518f5824]" name="init" is-config="true" duration-ms="49" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testFetchEntity()[pri:0, instance:cn.vko.core.db.util.TestDbSqlUtil@518f5824]" name="testFetchEntity" duration-ms="1" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testFetchLongIll()[pri:0, instance:cn.vko.core.db.util.TestDbSqlUtil@518f5824]" name="testFetchLongIll" duration-ms="1" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testFetchIntIll()[pri:0, instance:cn.vko.core.db.util.TestDbSqlUtil@518f5824]" name="testFetchIntIll" duration-ms="0" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testFetchSignleNormal()[pri:0, instance:cn.vko.core.db.util.TestDbSqlUtil@518f5824]" name="testFetchSignleNormal" duration-ms="3" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testFetchStringIll()[pri:0, instance:cn.vko.core.db.util.TestDbSqlUtil@518f5824]" name="testFetchStringIll" duration-ms="1" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testQueryEntity()[pri:0, instance:cn.vko.core.db.util.TestDbSqlUtil@518f5824]" name="testQueryEntity" duration-ms="10" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testQueryEntityIll()[pri:0, instance:cn.vko.core.db.util.TestDbSqlUtil@518f5824]" name="testQueryEntityIll" duration-ms="9" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testQueryEntityPager()[pri:0, instance:cn.vko.core.db.util.TestDbSqlUtil@518f5824]" name="testQueryEntityPager" duration-ms="2" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testQueryEntityPagerRecordCount()[pri:0, instance:cn.vko.core.db.util.TestDbSqlUtil@518f5824]" name="testQueryEntityPagerRecordCount" duration-ms="3" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testQueryIntAll()[pri:0, instance:cn.vko.core.db.util.TestDbSqlUtil@518f5824]" name="testQueryIntAll" duration-ms="1" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testQueryIntCastIll()[pri:0, instance:cn.vko.core.db.util.TestDbSqlUtil@518f5824]" name="testQueryIntCastIll" duration-ms="1" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
          <exception class="org.nutz.dao.DaoException">
            <message>
              <![CDATA[org.nutz.dao.DaoException: !Nutz SQL Error: 'select name from mock_entity_4_extend_query'
PreparedStatement: 
'select name from mock_entity_4_extend_query']]>
            </message>
            <full-stacktrace>
              <![CDATA[org.nutz.dao.DaoException: org.nutz.dao.DaoException: !Nutz SQL Error: 'select name from mock_entity_4_extend_query'
PreparedStatement: 
'select name from mock_entity_4_extend_query'
	at org.nutz.dao.impl.sql.run.NutDaoRunner.run(NutDaoRunner.java:76)
	at org.nutz.dao.impl.DaoSupport._exec(DaoSupport.java:199)
	at org.nutz.dao.impl.DaoSupport.execute(DaoSupport.java:177)
	at cn.vko.core.db.dao.impl.DbDao.excute(DbDao.java:170)
	at cn.vko.core.db.util.DbSqlUtil.getResult(DbSqlUtil.java:186)
	at cn.vko.core.db.util.DbSqlUtil.queryInt(DbSqlUtil.java:252)
	at cn.vko.core.db.util.DbSqlUtil.queryInt(DbSqlUtil.java:242)
	at cn.vko.core.db.util.DbSqlUtil.queryInt(DbSqlUtil.java:232)
	at cn.vko.core.db.util.TestDbSqlUtil.testQueryIntCastIll(TestDbSqlUtil.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
Caused by: org.nutz.dao.DaoException: !Nutz SQL Error: 'select name from mock_entity_4_extend_query'
PreparedStatement: 
'select name from mock_entity_4_extend_query'
	at org.nutz.dao.impl.sql.run.NutDaoExecutor.exec(NutDaoExecutor.java:90)
	at org.nutz.dao.impl.DaoSupport$DaoExec.invoke(DaoSupport.java:244)
	at org.nutz.dao.impl.sql.run.NutDaoRunner.run(NutDaoRunner.java:64)
	... 41 more
Caused by: org.h2.jdbc.JdbcSQLException: Data conversion error converting "测试0" [90021-140]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:156)
	at org.h2.value.Value.convertTo(Value.java:791)
	at org.h2.value.Value.getInt(Value.java:419)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:299)
	at org.nutz.dao.impl.sql.callback.QueryIntCallback.invoke(QueryIntCallback.java:21)
	at org.nutz.dao.impl.sql.NutSql.onAfter(NutSql.java:212)
	at org.nutz.dao.impl.sql.run.NutDaoExecutor._runSelect(NutDaoExecutor.java:225)
	at org.nutz.dao.impl.sql.run.NutDaoExecutor.exec(NutDaoExecutor.java:43)
	... 43 more
Caused by: java.lang.NumberFormatException: For input string: "测试0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:449)
	at java.lang.Integer.valueOf(Integer.java:528)
	at java.lang.Integer.decode(Integer.java:958)
	at org.h2.value.Value.convertTo(Value.java:748)
	... 49 more
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testQueryIntPager()[pri:0, instance:cn.vko.core.db.util.TestDbSqlUtil@518f5824]" name="testQueryIntPager" duration-ms="0" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testQueryIntIll()[pri:0, instance:cn.vko.core.db.util.TestDbSqlUtil@518f5824]" name="testQueryIntIll" duration-ms="0" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testQueryIntPagerRecordCount()[pri:0, instance:cn.vko.core.db.util.TestDbSqlUtil@518f5824]" name="testQueryIntPagerRecordCount" duration-ms="0" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
      </class>
      <class name="cn.vko.core.db.dao.impl.TestOperateDbDao">
        <test-method status="PASS" signature="init()[pri:0, instance:cn.vko.core.db.dao.impl.TestOperateDbDao@311671b2]" name="init" is-config="true" duration-ms="12" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testInsertArray()[pri:0, instance:cn.vko.core.db.dao.impl.TestOperateDbDao@311671b2]" name="testInsertArray" duration-ms="4" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testInsertCollection()[pri:0, instance:cn.vko.core.db.dao.impl.TestOperateDbDao@311671b2]" name="testInsertCollection" duration-ms="1" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testInsertMap()[pri:0, instance:cn.vko.core.db.dao.impl.TestOperateDbDao@311671b2]" name="testInsertMap" duration-ms="1" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[插入的数据不为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: 插入的数据不为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.OperateDbDao.insert(OperateDbDao.java:65)
	at cn.vko.core.db.dao.impl.TestOperateDbDao.testInsertMap(TestOperateDbDao.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testInsertSignle()[pri:0, instance:cn.vko.core.db.dao.impl.TestOperateDbDao@311671b2]" name="testInsertSignle" duration-ms="1" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testInsertNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestOperateDbDao@311671b2]" name="testInsertNull" duration-ms="0" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[插入的数据不为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: 插入的数据不为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.OperateDbDao.insert(OperateDbDao.java:65)
	at cn.vko.core.db.dao.impl.TestOperateDbDao.testInsertNull(TestOperateDbDao.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testInsertWithUserId()[pri:0, instance:cn.vko.core.db.dao.impl.TestOperateDbDao@311671b2]" name="testInsertWithUserId" duration-ms="1" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testUpdateArray()[pri:0, instance:cn.vko.core.db.dao.impl.TestOperateDbDao@311671b2]" name="testUpdateArray" duration-ms="3" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testUpdateCollection()[pri:0, instance:cn.vko.core.db.dao.impl.TestOperateDbDao@311671b2]" name="testUpdateCollection" duration-ms="2" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testUpdateMap()[pri:0, instance:cn.vko.core.db.dao.impl.TestOperateDbDao@311671b2]" name="testUpdateMap" duration-ms="0" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[插入的数据不为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: 插入的数据不为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.OperateDbDao.update(OperateDbDao.java:184)
	at cn.vko.core.db.dao.impl.TestOperateDbDao.testUpdateMap(TestOperateDbDao.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testUpdateSignle()[pri:0, instance:cn.vko.core.db.dao.impl.TestOperateDbDao@311671b2]" name="testUpdateSignle" duration-ms="2" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testUpdateNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestOperateDbDao@311671b2]" name="testUpdateNull" duration-ms="0" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[插入的数据不为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: 插入的数据不为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.OperateDbDao.update(OperateDbDao.java:184)
	at cn.vko.core.db.dao.impl.TestOperateDbDao.testUpdateNull(TestOperateDbDao.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
      <class name="cn.vko.core.db.util.TestRecordUtil">
        <test-method status="PASS" signature="init()[pri:0, instance:cn.vko.core.db.util.TestRecordUtil@2f833eca]" name="init" is-config="true" duration-ms="8" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testGetBoolean()[pri:0, instance:cn.vko.core.db.util.TestRecordUtil@2f833eca]" name="testGetBoolean" duration-ms="0" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testGetBooleanIll()[pri:0, instance:cn.vko.core.db.util.TestRecordUtil@2f833eca]" name="testGetBooleanIll" duration-ms="0" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testGetDateIll()[pri:0, instance:cn.vko.core.db.util.TestRecordUtil@2f833eca]" name="testGetDateIll" duration-ms="0" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testGetDouble()[pri:0, instance:cn.vko.core.db.util.TestRecordUtil@2f833eca]" name="testGetDouble" duration-ms="1" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testGetDoubleIll()[pri:0, instance:cn.vko.core.db.util.TestRecordUtil@2f833eca]" name="testGetDoubleIll" duration-ms="0" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testGetLongIll()[pri:0, instance:cn.vko.core.db.util.TestRecordUtil@2f833eca]" name="testGetLongIll" duration-ms="0" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testGetLong()[pri:0, instance:cn.vko.core.db.util.TestRecordUtil@2f833eca]" name="testGetLong" duration-ms="0" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
      </class>
      <class name="cn.vko.core.db.dao.impl.TestDbDao">
        <test-method status="PASS" signature="init()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="init" is-config="true" duration-ms="526" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testDeleteByIdNormal()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testDeleteByIdNormal" duration-ms="7" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testDeleteByIdNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testDeleteByIdNull" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[clazz不能为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: clazz不能为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkNull(ExceptionUtil.java:132)
	at cn.vko.core.db.dao.impl.DbDao.delete(DbDao.java:163)
	at cn.vko.core.db.dao.impl.TestDbDao.testDeleteByIdNull(TestDbDao.java:627)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testDeleteNormal()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testDeleteNormal" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testDeleteNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testDeleteNull" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[要删除的对象不能为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: 要删除的对象不能为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.DbDao.delete(DbDao.java:154)
	at cn.vko.core.db.dao.impl.TestDbDao.testDeleteNull(TestDbDao.java:622)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testDeleteWithoutId()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testDeleteWithoutId" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Don't know how to make fetch key cn.vko.core.db.mock.entity.MockEntityWithoutId:'MockEntityWithoutId(id=0, name=测试)']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Don't know how to make fetch key cn.vko.core.db.mock.entity.MockEntityWithoutId:'MockEntityWithoutId(id=0, name=测试)'
	at org.nutz.lang.Lang.makeThrow(Lang.java:96)
	at org.nutz.dao.util.Pojos$Items.cndAuto(Pojos.java:145)
	at org.nutz.dao.impl.EntityOperator.addDeleteSelfOnly(EntityOperator.java:145)
	at org.nutz.dao.impl.NutDao.delete(NutDao.java:342)
	at cn.vko.core.db.dao.impl.DbDao.delete(DbDao.java:158)
	at cn.vko.core.db.dao.impl.TestDbDao.testDeleteWithoutId(TestDbDao.java:634)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testFetchByClassByCnd()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testFetchByClassByCnd" duration-ms="5" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testExcuteNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testExcuteNull" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[sql对象不允许为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: sql对象不允许为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.DbDao.excute(DbDao.java:169)
	at cn.vko.core.db.dao.impl.TestDbDao.testExcuteNull(TestDbDao.java:663)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testFetchByClassById()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testFetchByClassById" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testFetchByClassByNotExistsId()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testFetchByClassByNotExistsId" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testFetchByCndNotHasId()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testFetchByCndNotHasId" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testFetchByClassNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testFetchByClassNull" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[class不能为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: class不能为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkNull(ExceptionUtil.java:132)
	at cn.vko.core.db.dao.impl.DbDao.fetch(DbDao.java:215)
	at cn.vko.core.db.dao.impl.TestDbDao.testFetchByClassNull(TestDbDao.java:509)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testFetchByIdNotHasId()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testFetchByIdNotHasId" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="org.nutz.dao.DaoException">
            <message>
              <![CDATA[Need @Id for class cn.vko.core.db.mock.entity.MockEntityWithoutId]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.nutz.dao.DaoException: Need @Id for class cn.vko.core.db.mock.entity.MockEntityWithoutId
	at org.nutz.dao.impl.NutDao.fetch(NutDao.java:456)
	at cn.vko.core.db.dao.impl.DbDao.fetch(DbDao.java:209)
	at cn.vko.core.db.dao.impl.TestDbDao.testFetchByIdNotHasId(TestDbDao.java:521)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testFetchBySql()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testFetchBySql" duration-ms="2" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testFetchBySqlNotExists()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testFetchBySqlNotExists" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testFetchByTableNameByCnd()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testFetchByTableNameByCnd" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testFetchBySqlNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testFetchBySqlNull" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[sql不能为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: sql不能为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.DbDao.fetch(DbDao.java:237)
	at cn.vko.core.db.dao.impl.TestDbDao.testFetchBySqlNull(TestDbDao.java:595)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testFetchByTableNameById()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testFetchByTableNameById" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testFetchByTableNameByNotExistsId()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testFetchByTableNameByNotExistsId" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testFetchByTableNameNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testFetchByTableNameNull" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[tableName不能为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: tableName不能为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.DbDao.fetch(DbDao.java:231)
	at cn.vko.core.db.dao.impl.TestDbDao.testFetchByTableNameNull(TestDbDao.java:515)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testInsertArray()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertArray" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testInsertArrayHasNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertArrayHasNull" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at cn.vko.core.db.dao.impl.DbDao$1.invoke(DbDao.java:79)
	at org.nutz.lang.Lang.each(Lang.java:1362)
	at org.nutz.lang.Lang.each(Lang.java:1326)
	at cn.vko.core.db.dao.impl.DbDao.insert(DbDao.java:71)
	at cn.vko.core.db.dao.impl.TestDbDao.testInsertArrayHasNull(TestDbDao.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testInsertArrayNotSame()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertArrayNotSame" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Invalid operating object 'cn.vko.core.db.mock.entity.MockEntityWithoutAutoId' for field ''id'(cn.vko.core.db.mock.entity.MockEntityWithAutoId)']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Invalid operating object 'cn.vko.core.db.mock.entity.MockEntityWithoutAutoId' for field ''id'(cn.vko.core.db.mock.entity.MockEntityWithAutoId)'
	at org.nutz.lang.Lang.makeThrow(Lang.java:96)
	at org.nutz.dao.impl.entity.macro.SqlFieldMacro.setOperatingObject(SqlFieldMacro.java:40)
	at org.nutz.dao.impl.EntityOperator.addInsert(EntityOperator.java:169)
	at org.nutz.dao.impl.NutDao$1.invoke(NutDao.java:130)
	at org.nutz.lang.Lang.each(Lang.java:1362)
	at org.nutz.dao.impl.NutDao.insert(NutDao.java:128)
	at cn.vko.core.db.dao.impl.DbDao.insert(DbDao.java:99)
	at cn.vko.core.db.dao.impl.TestDbDao.testInsertArrayNotSame(TestDbDao.java:219)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testInsertArrayNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertArrayNull" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[插入的数据不为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: 插入的数据不为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.DbDao.insert(DbDao.java:69)
	at cn.vko.core.db.dao.impl.TestDbDao.testInsertArrayNull(TestDbDao.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testInsertList()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertList" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testInsertCollectionNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertCollectionNull" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[插入的数据不为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: 插入的数据不为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.DbDao.insert(DbDao.java:69)
	at cn.vko.core.db.dao.impl.TestDbDao.testInsertCollectionNull(TestDbDao.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testInsertListHasNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertListHasNull" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at cn.vko.core.db.dao.impl.DbDao$1.invoke(DbDao.java:79)
	at org.nutz.lang.Lang.each(Lang.java:1373)
	at org.nutz.lang.Lang.each(Lang.java:1326)
	at cn.vko.core.db.dao.impl.DbDao.insert(DbDao.java:71)
	at cn.vko.core.db.dao.impl.TestDbDao.testInsertListHasNull(TestDbDao.java:259)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testInsertMap()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertMap" duration-ms="2" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testInsertMapNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertMapNull" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[插入的数据不为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: 插入的数据不为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.DbDao.insert(DbDao.java:69)
	at cn.vko.core.db.dao.impl.TestDbDao.testInsertMapNull(TestDbDao.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testInsertNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertNull" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[插入的数据不为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: 插入的数据不为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.DbDao.insert(DbDao.java:69)
	at cn.vko.core.db.dao.impl.TestDbDao.testInsertNull(TestDbDao.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testInsertSingleWithAutoIdHasId()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertSingleWithAutoIdHasId" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testInsertSingleWithAutoIdNotHasId()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertSingleWithAutoIdNotHasId" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testInsertSingleWithNotAutoIdNotHasId()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertSingleWithNotAutoIdNotHasId" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testInsertSingleWithoutIdNotHasId()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertSingleWithoutIdNotHasId" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testInsertTableByClass()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertTableByClass" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testInsertTableByClassClassNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertTableByClassClassNull" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[class不能为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: class不能为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkNull(ExceptionUtil.java:132)
	at cn.vko.core.db.dao.impl.DbDao.insert(DbDao.java:112)
	at cn.vko.core.db.dao.impl.TestDbDao.testInsertTableByClassClassNull(TestDbDao.java:280)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testInsertTableByClassChainNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertTableByClassChainNull" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[chain不能为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: chain不能为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkNull(ExceptionUtil.java:132)
	at cn.vko.core.db.dao.impl.DbDao.insert(DbDao.java:113)
	at cn.vko.core.db.dao.impl.TestDbDao.testInsertTableByClassChainNull(TestDbDao.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testInsertTableByTableName()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertTableByTableName" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testInsertTableByTableNameChainNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertTableByTableNameChainNull" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[chain不能为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: chain不能为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkNull(ExceptionUtil.java:132)
	at cn.vko.core.db.dao.impl.DbDao.insert(DbDao.java:106)
	at cn.vko.core.db.dao.impl.TestDbDao.testInsertTableByTableNameChainNull(TestDbDao.java:302)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testInsertTableByTableNameTabelNameNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertTableByTableNameTabelNameNull" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[tableName不能为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: tableName不能为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.DbDao.insert(DbDao.java:105)
	at cn.vko.core.db.dao.impl.TestDbDao.testInsertTableByTableNameTabelNameNull(TestDbDao.java:297)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testInsertWithOutAutoHasId()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testInsertWithOutAutoHasId" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testQueryByClass()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testQueryByClass" duration-ms="2" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testQueryByClassClazzNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testQueryByClassClazzNull" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[查询的类型不为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: 查询的类型不为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkNull(ExceptionUtil.java:132)
	at cn.vko.core.db.dao.impl.DbDao.query(DbDao.java:176)
	at cn.vko.core.db.dao.impl.TestDbDao.testQueryByClassClazzNull(TestDbDao.java:669)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testQueryByClassCnd()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testQueryByClassCnd" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testQueryByClassCndAndPagerNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testQueryByClassCndAndPagerNull" duration-ms="3" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testQueryBySql()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testQueryBySql" duration-ms="2" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testQueryBySqlCnd()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testQueryBySqlCnd" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testQueryBySqlCndAndPagerNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testQueryBySqlCndAndPagerNull" duration-ms="2" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testQueryByTableName()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testQueryByTableName" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testQueryBySqlSqlNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testQueryBySqlSqlNull" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[sql对象不允许为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: sql对象不允许为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkNull(ExceptionUtil.java:132)
	at cn.vko.core.db.dao.impl.DbDao.query(DbDao.java:191)
	at cn.vko.core.db.dao.impl.TestDbDao.testQueryBySqlSqlNull(TestDbDao.java:726)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testQueryByTableNameCnd()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testQueryByTableNameCnd" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testQueryByTableNameCndAndPagerNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testQueryByTableNameCndAndPagerNull" duration-ms="3" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testQueryByTableNameTableNameNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testQueryByTableNameTableNameNull" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[查询的表不为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: 查询的表不为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.DbDao.query(DbDao.java:183)
	at cn.vko.core.db.dao.impl.TestDbDao.testQueryByTableNameTableNameNull(TestDbDao.java:675)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testUpdateArrayAll()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testUpdateArrayAll" duration-ms="3" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testUpdateArrayParty()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testUpdateArrayParty" duration-ms="2" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testUpdateByClassTableNameNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testUpdateByClassTableNameNull" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[类型不能为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: 类型不能为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkNull(ExceptionUtil.java:132)
	at cn.vko.core.db.dao.impl.DbDao.update(DbDao.java:146)
	at cn.vko.core.db.dao.impl.TestDbDao.testUpdateByClassTableNameNull(TestDbDao.java:498)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testUpdateListAll()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testUpdateListAll" duration-ms="3" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testUpdateByTableNameTableNameNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testUpdateByTableNameTableNameNull" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[表名不能为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: 表名不能为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.DbDao.update(DbDao.java:137)
	at cn.vko.core.db.dao.impl.TestDbDao.testUpdateByTableNameTableNameNull(TestDbDao.java:492)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testUpdateListParty()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testUpdateListParty" duration-ms="2" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testUpdateObjNull()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testUpdateObjNull" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[更新的对象不允许为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: 更新的对象不允许为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.DbDao.update(DbDao.java:119)
	at cn.vko.core.db.dao.impl.TestDbDao.testUpdateObjNull(TestDbDao.java:312)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testUpdateMap()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testUpdateMap" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[更新的对象不允许为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: 更新的对象不允许为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkEmpty(ExceptionUtil.java:147)
	at cn.vko.core.db.dao.impl.DbDao.update(DbDao.java:119)
	at cn.vko.core.db.dao.impl.TestDbDao.testUpdateMap(TestDbDao.java:503)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testUpdateSingleAll()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testUpdateSingleAll" duration-ms="1" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testUpdateSingleParty()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testUpdateSingleParty" duration-ms="2" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
        </test-method>
        <test-method status="PASS" signature="testUpdateWithoutIdParty()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testUpdateWithoutIdParty" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Don't know how to make fetch key cn.vko.core.db.mock.entity.MockEntityWithoutId:'MockEntityWithoutId(id=0, name=测试)']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Don't know how to make fetch key cn.vko.core.db.mock.entity.MockEntityWithoutId:'MockEntityWithoutId(id=0, name=测试)'
	at org.nutz.lang.Lang.makeThrow(Lang.java:96)
	at org.nutz.dao.util.Pojos$Items.cndAuto(Pojos.java:145)
	at org.nutz.dao.impl.EntityOperator.addUpdate(EntityOperator.java:74)
	at org.nutz.dao.impl.EntityOperator.addUpdate(EntityOperator.java:56)
	at org.nutz.dao.impl.NutDao.update(NutDao.java:210)
	at org.nutz.dao.impl.NutDao$2.run(NutDao.java:225)
	at org.nutz.dao.FieldFilter.run(FieldFilter.java:285)
	at org.nutz.dao.impl.NutDao.update(NutDao.java:228)
	at cn.vko.core.db.dao.impl.DbDao.update(DbDao.java:131)
	at cn.vko.core.db.dao.impl.TestDbDao.testUpdateWithoutIdParty(TestDbDao.java:324)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testUpdateWithoutId()[pri:0, instance:cn.vko.core.db.dao.impl.TestDbDao@19e3cd51]" name="testUpdateWithoutId" duration-ms="0" started-at="2014-05-15T19:29:05Z" finished-at="2014-05-15T19:29:05Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Don't know how to make fetch key cn.vko.core.db.mock.entity.MockEntityWithoutId:'MockEntityWithoutId(id=0, name=测试)']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Don't know how to make fetch key cn.vko.core.db.mock.entity.MockEntityWithoutId:'MockEntityWithoutId(id=0, name=测试)'
	at org.nutz.lang.Lang.makeThrow(Lang.java:96)
	at org.nutz.dao.util.Pojos$Items.cndAuto(Pojos.java:145)
	at org.nutz.dao.impl.EntityOperator.addUpdate(EntityOperator.java:74)
	at org.nutz.dao.impl.EntityOperator.addUpdate(EntityOperator.java:56)
	at org.nutz.dao.impl.NutDao.update(NutDao.java:210)
	at cn.vko.core.db.dao.impl.DbDao.update(DbDao.java:124)
	at cn.vko.core.db.dao.impl.TestDbDao.testUpdateWithoutId(TestDbDao.java:318)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
      <class name="cn.vko.core.db.util.TestDbExendUtil">
        <test-method status="PASS" signature="init()[pri:0, instance:cn.vko.core.db.util.TestDbExendUtil@3882764b]" name="init" is-config="true" duration-ms="48" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testAbleMulipt()[pri:0, instance:cn.vko.core.db.util.TestDbExendUtil@3882764b]" name="testAbleMulipt" duration-ms="6" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testAbleSignleNoral()[pri:0, instance:cn.vko.core.db.util.TestDbExendUtil@3882764b]" name="testAbleSignleNoral" duration-ms="2" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testCount()[pri:0, instance:cn.vko.core.db.util.TestDbExendUtil@3882764b]" name="testCount" duration-ms="2" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testCountCnd()[pri:0, instance:cn.vko.core.db.util.TestDbExendUtil@3882764b]" name="testCountCnd" duration-ms="2" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testCountNull()[pri:0, instance:cn.vko.core.db.util.TestDbExendUtil@3882764b]" name="testCountNull" duration-ms="1" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
          <exception class="cn.vko.core.common.exception.impl.ParamException">
            <message>
              <![CDATA[类型不能为空]]>
            </message>
            <full-stacktrace>
              <![CDATA[cn.vko.core.common.exception.impl.ParamException: 类型不能为空
	at cn.vko.core.common.util.ExceptionUtil.pEx(ExceptionUtil.java:103)
	at cn.vko.core.common.util.ExceptionUtil.checkNull(ExceptionUtil.java:132)
	at cn.vko.core.db.util.EntityUtil.getTableName(EntityUtil.java:46)
	at cn.vko.core.db.util.DbExtendUtil.count(DbExtendUtil.java:54)
	at cn.vko.core.db.util.DbExtendUtil.count(DbExtendUtil.java:38)
	at cn.vko.core.db.util.TestDbExendUtil.testCountNull(TestDbExendUtil.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:78)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testDisableStatus()[pri:0, instance:cn.vko.core.db.util.TestDbExendUtil@3882764b]" name="testDisableStatus" duration-ms="1" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
        <test-method status="PASS" signature="testEnableStatus()[pri:0, instance:cn.vko.core.db.util.TestDbExendUtil@3882764b]" name="testEnableStatus" duration-ms="2" started-at="2014-05-15T19:29:06Z" finished-at="2014-05-15T19:29:06Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
